### ISSUE TITLE
algorithm checklist #1

### ISSUE THREAD

**Issue by sebbbin** [sebbbin/Boj#1]
#### 200 - 자료구조 1
- [x] 스택 
- [x] 단어 뒤집기 
- [ ] 괄호
- [x] 스택 수열
- [ ] 에디터
- [ ] 큐
- [ ] 조세퍼스 문제
- [ ] 덱
#### 201 - 자료구조 1 (연습)
- [ ] 단어 뒤집기 2
- [ ] 쇠막대기
- [ ] 오큰수
- [ ] 오등큰수
#### 203 - 자료구조 1 (참고)
- [ ] 후위 표기식2
- [ ] 후위 표기식
- [ ] 알파벳 개수
- [ ] 알파벳 찾기
- [ ] 문자열 분석
- [ ] 단어 길이 재기
- [ ] ROT13
- [ ] 네 수
- [ ] 접미사 배열
#### 300 - 수학 1
- [ ] 나머지
- [ ] 최대공약수와 최소공배수
- [x] 최소공배수
- [ ] 소수 찾기
- [ ] 소수 구하기
- [ ] 골드바흐의 추측
- [ ] 팩토리얼
- [ ] 팩토리얼 0의 개수
- [ ] 조합 0의 개수
#### 301 - 수학 1 (연습)
- [ ] GCD 합
- [ ] 숨바꼭질 6
- [ ] 2진수 8진수
- [ ] 8진수 2진수
- [ ] 2진수
- [ ] 골드바흐 파티션
#### 303 - 수학 1 (참고)
- [ ] 진법 변환 2
- [ ] 진법 변환
- [ ] Base Conversion
- [ ] 소인수분해
#### 400 - 다이나믹 프로그래밍 1
- [ ] 1로 만들기
- [ ] 2×n 타일링
- [ ] 2×n 타일링 2
- [ ] 1, 2, 3 더하기
- [ ] 카드 구매하기
- [ ] 카드 구매하기 2
- [ ] 1, 2, 3 더하기 5
- [ ] 쉬운 계단 수
- [ ] 이친수
- [ ] 가장 긴 증가하는 부분 수열
- [ ] 가장 긴 증가하는 부분 수열 4
- [ ] 연속합
- [ ] 제곱수의 합
- [ ] 합분해
#### 401 - 다이나믹 프로그래밍 1 (연습)
- [ ] 1, 2, 3 더하기 3
- [ ] RGB거리
- [ ] 동물원
- [ ] 오르막 수
- [ ] 스티커
- [ ] 포도주 시식
- [ ] 정수 삼각형
- [ ] 가장 큰 증가 부분 수열
- [ ] 가장 긴 감소하는 부분 수열
- [ ] 가장 긴 바이토닉 부분 수열
- [ ] 연속합 2
- [ ] 타일 채우기
#### 402 - 다이나믹 프로그래밍 1 (도전)
- [ ] 동물원
- [ ] RGB거리 2
- [ ] 합분해
